# Generated by Django 4.2.7 on 2025-07-22 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='event_parti_event_i_fdf78f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['registered_at'], name='event_parti_registe_36adcd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['is_active'], name='event_parti_is_acti_e7c2dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'time'], name='events_date_49fc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_created_2c88fa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_is_acti_45ba60_idx'),
        ),
    ]
