# Generated by Django 4.2.7 on 2025-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_update', 'Event Update'), ('event_cancellation', 'Event Cancellation'), ('registration_confirmation', 'Registration Confirmation'), ('reminder', 'Event Reminder')], max_length=50, verbose_name='notification type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('event_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='event id')),
                ('event_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='event title')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
